<script setup>
/**
 * SYSTEM LOGS & MONITORING
 * This view provides an unified administrative oversight of all clinical activity, 
 * historical record creation, and real-time scheduling.
 */
import { ref, computed } from 'vue'
import DashboardLayout from '../../components/layout/DashboardLayout.vue'
import BaseCard from '../../components/base/BaseCard.vue'
import BaseButton from '../../components/base/BaseButton.vue'
import { useAppointmentStore } from '../../stores/appointmentStore'
import { useRecordStore } from '../../stores/recordStore'

// Access clinical data repositories.
const appointmentStore = useAppointmentStore()
const recordStore = useRecordStore()

// --- UI STATE ---
// Reactive filters for granular control over the log display.
const filterRole = ref('all')
const filterStatus = ref('all')

// --- DATA DERIVATION ---
/**
 * allAppointments - Computed list of all system appointments, sorted chronologically.
 * Uses the store's central array.
 */
const allAppointments = computed(() => {
  return appointmentStore.appointments.slice().sort((a, b) => b.id - a.id)
})

/**
 * systemActivity - A high-level audit trail generated by merging multiple system events.
 * It combines 'Appointment' and 'Record' creation events into a single chronological timeline.
 * Limited to the latest 15 events for performance and oversight clarity.
 */
const systemActivity = computed(() => {
  const events = [
    // Transform appointment objects into unified event objects.
    ...appointmentStore.appointments.map(a => ({
      id: `apt-${a.id}`,
      type: 'appointment',
      title: 'New Appointment',
      desc: `${a.patientName} booked with ${a.doctor}`,
      time: a.date,
      status: a.status
    })),
    // Transform record objects into unified event objects.
    ...recordStore.records.map(r => ({
      id: `rec-${r.id}`,
      type: 'record',
      title: 'Clinical Record',
      desc: `Record created for patient admission`,
      time: r.date,
      status: 'saved'
    }))
  ]
  
  // Sort by ID (effectively chronological with the current mock data structure).
  return events.sort((a, b) => b.id.split('-')[1] - a.id.split('-')[1]).slice(0, 15)
})
</script>

<template>
  <DashboardLayout>
    <!-- Page title defined in the standard header slot -->
    <template #header-title>System Monitoring</template>

    <div class="logs-container">
      <!-- 
        SYSTEM ACTIVITY TIMELINE 
        A narrow sidebar feed showing the most recent system mutations.
      -->
      <BaseCard title="Real-time Audit Trail" class="timeline-card">
        <template #header>
          <div class="card-header">
            <h2>System Activity Log</h2>
            <p class="subtitle">Real-time tracking of clinical bookings and record creation.</p>
          </div>
        </template>
        
        <div class="audit-trail">
          <!-- Iterate through unified system activity events -->
          <div v-for="event in systemActivity" :key="event.id" class="audit-item">
            <!-- Icon marker styled based on event type -->
            <div class="audit-marker" :class="event.type"></div>
            <div class="audit-content">
              <div class="audit-main">
                <span class="audit-title">{{ event.title }}</span>
                <span class="audit-desc">{{ event.desc }}</span>
              </div>
              <div class="audit-meta">
                <span class="audit-time">{{ event.time }}</span>
                <span :class="['audit-status', event.status]">{{ event.status }}</span>
              </div>
            </div>
          </div>
          
          <!-- Fallback for empty activity feed -->
          <div v-if="systemActivity.length === 0" class="empty-logs">
            <p>No system activity detected yet.</p>
          </div>
        </div>
      </BaseCard>

      <!-- 
        APPOINTMENT MONITORING 
        A master table of all scheduled clinical consultations across the platform.
      -->
      <BaseCard title="Global Appointment Monitor">
        <template #header>
          <div class="card-header">
            <div>
              <h2>Appointment Traffic</h2>
              <p class="subtitle">Centralized oversight of all scheduled clinical consultations.</p>
            </div>
            <!-- Filter controls for the master table -->
            <div class="filter-group">
              <select v-model="filterStatus" class="styled-select-sm" aria-label="Filter by appointment status">
                <option value="all">All Status</option>
                <option value="pending">Pending</option>
                <option value="approved">Approved</option>
                <option value="completed">Completed</option>
              </select>
            </div>
          </div>
        </template>

        <!-- Master Data Table -->
        <div class="table-wrapper">
          <table class="monitor-table">
            <thead>
              <tr>
                <th>Patient</th>
                <th>Provider</th>
                <th>Schedule</th>
                <th>Status</th>
                <th class="text-right">Action</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="apt in allAppointments" :key="apt.id">
                <td><span class="strong">{{ apt.patientName }}</span></td>
                <td>{{ apt.doctor }}</td>
                <td>
                  <div class="schedule-cell">
                    <span class="date">{{ apt.date }}</span>
                    <span class="time">{{ apt.time }}</span>
                  </div>
                </td>
                <td>
                  <span :class="['status-pill', apt.status]">{{ apt.status }}</span>
                </td>
                <td class="text-right">
                  <!-- Administrative override: Irreversible cancellation of clinic appointments -->
                  <button @click="appointmentStore.deleteAppointment(apt.id)" class="btn-cancel">Cancel Appt</button>
                </td>
              </tr>
            </tbody>
          </table>
          
          <!-- Empty list indicator -->
          <div v-if="allAppointments.length === 0" class="empty-monitor">
            <p>No appointments found in the system registry.</p>
          </div>
        </div>
      </BaseCard>
    </div>
  </DashboardLayout>
</template>

<style scoped>
/* Master layout split: Narrow activity feed on the left, wide table on the right */
.logs-container {
  max-width: 1200px;
  margin: 0 auto;
  display: grid;
  grid-template-columns: 350px 1fr;
  gap: 2rem;
  align-items: start;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.subtitle {
  color: var(--text-dim);
  font-size: 0.8rem;
  margin-top: 0.25rem;
  font-weight: 600;
}

/* AUDIT TRAIL: Vertical list of circular markers and text labels */
.audit-trail {
  display: flex;
  flex-direction: column;
  gap: 1.25rem;
}

.audit-item {
  display: flex;
  gap: 1rem;
  padding-bottom: 1.25rem;
  border-bottom: 1px solid var(--glass-border);
}

.audit-item:last-child { border-bottom: none; padding-bottom: 0; }

.audit-marker {
  width: 10px;
  height: 10px;
  border-radius: 50%;
  margin-top: 6px;
  flex-shrink: 0;
}

/* Event-specific telemetry markers */
.audit-marker.appointment { background: #4f46e5; box-shadow: 0 0 10px rgba(79, 70, 229, 0.4); }
.audit-marker.record { background: #059669; box-shadow: 0 0 10px rgba(5, 150, 105, 0.4); }

.audit-content { flex: 1; }
.audit-main { display: flex; flex-direction: column; }
.audit-title { font-weight: 700; font-size: 0.9rem; }
.audit-desc { font-size: 0.8rem; color: var(--text-dim); }

.audit-meta {
  display: flex;
  justify-content: space-between;
  margin-top: 0.5rem;
}

.audit-time { font-size: 0.7rem; font-weight: 700; color: var(--text-dim); }
.audit-status { font-size: 0.65rem; font-weight: 800; text-transform: uppercase; color: var(--primary-main); }

/* MONITOR TABLE: High-density clinical interaction registry */
.monitor-table {
  width: 100%;
  border-collapse: collapse;
}

.monitor-table th {
  text-align: left;
  padding: 1rem;
  font-size: 0.7rem;
  text-transform: uppercase;
  color: var(--text-dim);
  background: var(--bg-muted);
  border-bottom: 2px solid var(--glass-border);
}

.monitor-table td {
  padding: 1.25rem 1rem;
  border-bottom: 1px solid var(--glass-border, rgba(0, 0, 0, 0.05));
  font-size: 0.95rem;
}

.strong { font-weight: 700; }

.schedule-cell { display: flex; flex-direction: column; }
.schedule-cell .time { font-size: 0.8rem; font-weight: 700; color: var(--primary-main); }

/* Standard status pill indicators */
.status-pill {
  font-size: 0.7rem;
  font-weight: 800;
  padding: 0.25rem 0.6rem;
  border-radius: 6px;
  text-transform: uppercase;
}

.status-pill.pending { background: rgba(234, 179, 8, 0.1); color: #d97706; }
.status-pill.approved { background: rgba(59, 130, 246, 0.1); color: var(--primary-main); }
.status-pill.completed { background: rgba(16, 185, 129, 0.1); color: #059669; }

.text-right { text-align: right; }

.btn-cancel {
  background: none;
  border: none;
  color: #dc2626;
  font-size: 0.8rem;
  font-weight: 700;
  cursor: pointer;
  opacity: 0.6;
}

.btn-cancel:hover { opacity: 1; text-decoration: underline; }

/* Filter dropdown styling */
.styled-select-sm {
  padding: 0.4rem 0.75rem;
  border-radius: 8px;
  border: 1px solid var(--glass-border);
  background: var(--bg-faint);
  color: var(--text-main);
  font-size: 0.85rem;
  outline: none;
}

/* Fallback message styling for empty views */
.empty-logs, .empty-monitor {
  text-align: center;
  padding: 3rem;
  color: var(--text-dim);
  font-style: italic;
}

/* Stack the grid columns for mobile/tablet screens */
@media (max-width: 1000px) {
  .logs-container { grid-template-columns: 1fr; }
}
</style>
